language: csharp
mono: none
dotnet: 3.1.200
install:
- dotnet restore
script:
- dotnet publish -c Release
deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: $AZURE_WA_SITE